# Generated by Django 5.0.4 on 2024-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0003_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
