# Generated by Django 5.0.4 on 2024-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0009_remove_order_date_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
