# Generated by Django 5.0.4 on 2024-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0010_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
