# Generated by Django 5.0.4 on 2024-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0011_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
