# Generated by Django 5.0.4 on 2024-07-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafters', '0012_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
